### ISSUE TITLE
Create /u/{short_url} route

### ISSUE THREAD

**Issue by mikerogne** [mikerogne/url-shortener#4]
Should look up & redirect to the long (original) URL.
If it does not exist, should return 404.

**Comment by bkilshaw** [comment]
What about skipping the /u/ altogether and just have domain.com/{slug} ?  Saves 3 characters

**Comment by mikerogne** [comment]
Yeah I thought about it, but I think for now just keep /u/.

**Comment by mikerogne** [comment]
I mean it doesn't REALLY matter. If you feel strongly about just domain.com/{slug} go for it! I'll accept it.
